# sushi-config.yaml is documented https://fshschoolA.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
id: ihe.iti.vhl
canonical: https://profiles.ihe.net/ITI/VHL
version: 0.0.2-current
name: IHE_ITI_VHL
title: "Verified Health Link"
description: Patient Mediated sharing of their health information using internet accessible verifiable health link.
releaseLabel: ci-build
#releaseLabel: ballot
#releaseLabel: trial-use
#releaseLabel: release
date: 2025-03-07
status: draft
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
license: CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2024+


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

  produce-jekyll-data: true

#resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate. The order they appear here is the order they will appear in the TOC and on the next/prev navigation.
  index.md:
    title: ToDo Home
    generation: markdown
  volume-1.md:
    title: 1:XX Verifiable Health Links (VHL) - Volume 1
    generation: markdown
  volume-2.md:
    title: "2: Verifiable Health Links (VHL) - Volume 2"
    generation: markdown

  volume-3.md:
    title: 3:3 Verifiable Health Links (VHL) - Volume 3
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  other.md:
    title: Changes to Other IHE Specifications
    generation: markdown
  vhl_vs_shl.md:
    title: "Appendix A: Comparision of health links"
  download.md:
    title: "Download and Analysis"
    generation: markdown
  issues.md:
    title: Significant Changes and Issues
    generation: markdown

menu:
  Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#actors-and-transactions
    Actor Options: volume-1.html#actor-options
    Required Actor Groupings: volume-1.html#required-groupings
    Overview: volume-1.html#overview
    Security Considerations: volume-1.html#security-considerations
    Cross-Profile Considerations: volume-1.html#other-grouping
  Volume 2:
    Generate VHL: generate_vhl.html
  Volume 3:
    Content Profiles: volume-3.html
  Artifacts: artifacts.html
  Other:
    Changes to Other IHE Specifications: other.html
    Download and Analysis: download.html
    Test Plan: testplan.html
    Appendix A (VHL vs SHL): vhl_vs_shl.html
